USER_ROLES = ["default", "moderator"]
SITE_STATUSES = ["suggested", "broken"]
SITE_CATEGORY_RELATIONSHIPS = ["tag"]
SITE_CATEGORY_STATUSES = ["suggested"]
USER_CATEGORY_RELATIONSHIPS = ["like"]
USER_SITE_RELATIONSHIPS = ["like", "dislike", "visited", "collection"]
