version: "3.8"
services:
  random-walk-db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "15432:5432"
    # networks:
    #   - stumble

  random-walk-main:
    container_name: random_walk_main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:8000"
    # command:
      # - source venv/bin/activate
      # - python3 test.py
    # networks:
    #   - stumble
    environment:
      - DATABASE_URL=postgresql+asyncpg://admin_user:db_password@random-walk-db:5432/postgres  # Point FastAPI to the PostgreSQL container
    depends_on:
      - random-walk-db
